server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

app:
  name: "universal-service"
  version: "1.0.0"
  debug: true

providers:
  logger:
    type: "structured"
    level: "debug"
    service_name: "universal-service"
    format: "text"
    fields:
      environment: "development"

  metrics:
    type: "simple"
    enabled: true
    port: 9090
    path: "/metrics"
    service_name: "universal-service"

  auth:
    type: "simple"
    secret: "dev-secret-key-change-in-production"
    algorithm: "HS256"
    access_ttl: "24h"
    refresh_ttl: "168h" # 7 days

  cache:
    type: "memory"
    default_ttl: "1h"

  database:
    type: "postgres"
    host: "${DB_HOST:-localhost}"
    port: ${DB_PORT:-5432}
    username: "${DB_USERNAME:-postgres}"
    password: "${DB_PASSWORD:-password}"
    database: "${DB_DATABASE:-universal_service_dev}"
    ssl_mode: "disable"
    timezone: "UTC"
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: "1h"
    conn_max_idle_time: "30m"