server:
  host: "localhost"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

app:
  name: "universal-service"
  version: "1.0.0-local"
  debug: true

providers:
  logger:
    type: "simple"
    level: "debug"
    service_name: "universal-service"
    format: "text"

  metrics:
    type: "simple"
    enabled: true
    port: 9090
    path: "/metrics"
    service_name: "universal-service"

  auth:
    type: "simple"
    secret: "local-secret-key"
    algorithm: "HS256"

  cache:
    type: "memory"
    default_ttl: "30m"

  database:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "password"
    database: "universal_service_local"
    ssl_mode: "disable"
    timezone: "UTC"
    max_open_conns: 5
    max_idle_conns: 2